export const STORE_BOOKS_LIST_DATA = 'STORE_BOOKS_LIST_DATA'
export const CACHE_BOOK_TO_DELETE = "CACHE_BOOK_TO_DELETE"
export const PROMPT_ADD_BOOK = 'PROMPT_ADD_BOOK'
export const PROMPT_DELETE_BOOK = 'PROMPT_DELETE_BOOK'
export const PROMPT_SIGN_UP = 'PROMPT_SIGN_UP'